apps:
- name: DB
  cwd: ./back-end
  script: npm
  args: "start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  env:
    PORT: 3001
- name: DB
  cwd: ./front-end
  script: npm
  args: "run start:build"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  env:
    PORT: 3000
